services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./test.db
    depends_on:
      - db

  db:
    image: nouchka/sqlite3
    volumes:
      - ./data:/data
    environment:
      - SQLITE_DATABASE=/data/database.sqlite